# Site settings
author: Michael David Sackstein
title: 
header-img: img/home-bg.png
email: m_sackstein@yahoo.com
copyright_name: Michael David Sackstein
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: mds2465
github_username:  musiccity365

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
